### ISSUE TITLE
What is gapThreshold 

### ISSUE THREAD

**Issue by mziadd** [mapbox/geosimplify-js#2]
Is there any wiki to learn about it ?

**Comment by tdillon** [comment]
@mohammedX6 checkout these links to the source which discuss the details of `gapThreshold`.

https://github.com/mapbox/geosimplify-js/blob/master/README.md?plain=1#L21

https://github.com/mapbox/geosimplify-js/blob/master/geosimplify.js#L47-L48

FWIW, from my testing, the `gapThreshold` parameter does not work.

**Comment by mziadd** [comment]
Thanks
